name: live
description: Peeq Live

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.27+27

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: 3.2.0
  flutter_cache_manager: 3.3.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1
  progress_dialog: 1.2.4
  easy_localization: 3.0.0
  fluttertoast: 8.0.7
  shared_preferences: 2.0.5
  flutter_switch: 0.3.1
  quiver: ^3.0.1
  in_app_update: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  #  firebase_crashlytics: ^2.0.6
  flutter_bloc: ^7.2.0
  dynamic_themes: ^1.1.0
  flutter_flavorizr: ^2.0.0
  otp_text_field: ^1.1.1
  intl_phone_number_input: ^0.7.0+2
  dio: ^4.0.0
  jitsi_meet: ^4.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  permission_handler: 8.3.0
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  flutter_datetime_picker: ^1.5.1
  functional_widget_annotation: ^0.9.0+1
#  aws_s3_upload: ^1.2.0
#  amplify_storage_s3: ^0.2.4
#  amplify_flutter: ^0.2.4
  lottie: ^1.2.1
  flutter_native_splash: ^1.2.3
  web_socket_channel: ^2.1.0
  socket_io_client: ^1.0.2
  filesize: ^2.0.1
  video_player: ^2.2.7
  file_picker: ^4.2.7
  camera: ^0.9.4+5
  path_provider: 2.0.7
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  cupertino_icons: ^1.0.0
  agora_rtc_engine: ^4.0.7
  awesome_notifications: ^0.6.19

  #  flutter_ios_voip_kit:
#    path: ../flutter_ios_voip_kit
  #  flutter_callkit_incoming:
  #    git:
  #      url: https://gitlab.com/dristisushan/flutter_ios_voip_kit.git
  #      ref: main

  flutter_ios_voip_kit:
    git:
      url: https://gitlab.com/dristisushan/flutter_ios_voip_kit
      ref: main
  carousel_slider: ^4.0.0
  share_plus:
  sliding_up_panel: ^2.0.0+1
  rammus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  functional_widget: ^0.9.2
  build_runner: ^2.1.2
  pigeon: ^1.0.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-BlackItalic.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-BoldItalic.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/fonts/Poppins-ExtraBoldItalic.ttf
    - assets/fonts/Poppins-ExtraLight.ttf
    - assets/fonts/Poppins-ExtraLightItalic.ttf
    - assets/fonts/Poppins-Italic.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-LightItalic.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-MediumItalic.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-SemiBoldItalic.ttf
    - assets/fonts/Poppins-Thin.ttf
    - assets/fonts/Poppins-ThinItalic.ttf
    - assets/fonts/Heebo-Black.ttf
    - assets/fonts/Heebo-Bold.ttf
    - assets/fonts/Heebo-ExtraBold.ttf
    - assets/fonts/Heebo-Light.ttf
    - assets/fonts/Heebo-Medium.ttf
    - assets/fonts/Heebo-Regular.ttf
    - assets/fonts/Heebo-Thin.ttf
    - assets/fonts/manrope-bold.otf
    - assets/fonts/manrope-extrabold.otf
    - assets/fonts/manrope-light.otf
    - assets/fonts/manrope-medium.otf
    - assets/fonts/manrope-regular.otf
    - assets/fonts/manrope-semibold.otf
    - assets/fonts/manrope-thin.otf
    - assets/svg/peeq_text_logo.svg
    - assets/svg/icon_app.svg
    - assets/svg/Home.svg
    - assets/svg/threeDots.svg
    - assets/svg/arrowLeft.svg
    - assets/svg/MicrophoneOff.svg
    - assets/svg/MicrophoneOn.svg
    - assets/svg/Speaker.svg
    - assets/svg/CloseX.svg
    - assets/svg/CallEnd.svg
    - assets/svg/CameraFlip.svg
    - assets/svg/SpeakerOff.svg
    - assets/svg/Videomute.svg
    - assets/svg/Plus.svg
    - assets/svg/Chat.svg
    - assets/svg/User.svg
    - assets/svg/Shoppingcart.svg
    - assets/svg/Pluscircle.svg
    - assets/svg/Creditcard.svg
    - assets/svg/folder.svg
    - assets/svg/Hamburger.svg
    - assets/svg/message.svg
    - assets/svg/live.svg
    - assets/svg/Path.svg
    - assets/svg/Users.svg
    - assets/svg/NewUsers.svg
    - assets/svg/downButton.svg
    - assets/svg/Search.svg
    - assets/svg/NewHamburger.svg
    - assets/svg/newMessage.svg
    - assets/svg/NewHome.svg
    - assets/svg/rightButton.svg
    - assets/svg/Videocamera.svg
    - assets/svg/icon_app_mono.svg
    - assets/images/icon_image_border.png
    - assets/images/icon_home_image_border.png
    - assets/images/icon_home_image_border_oval.png
    - assets/images/icon_profile.png
    - assets/images/logo.png
    - assets/images/dashboardLogo.png
    - assets/images/icon_crown.png
    - assets/images/icon_notification_permission.png
    - assets/images/icon_wave.png
    - assets/images/icon_background.png
    - assets/images/userProfile.png
    - assets/images/icon_medical_background.jpg
    - assets/images/UserAvatar.png
    - assets/images/shopping.jpg
    - assets/images/jewellery.jpg
    - assets/images/virani.png
    - assets/images/virani.jpg
    - assets/images/logo_full.png
    - assets/images/avatar.jpg
    - assets/langs/en-US.json
    - assets/langs/fr-FR.json
    - assets/langs/zh-CN.json
    - assets/lottie/lottie_card_payment.json
    - assets/lottie/lottie_editor.json
    - assets/lottie/lottie_layer.json
    - assets/lottie/lottie_line_loader.json
    - assets/lottie/Peeq_loader.json
  fonts:
    - family: InterBlack
      fonts:
          - asset: assets/fonts/Inter-Black.ttf
    - family: InterBold
      fonts:
          - asset: assets/fonts/Inter-Bold.ttf
    - family: InterExtraBold
      fonts:
          - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: InterExtraLight
      fonts:
          - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: InterLight
      fonts:
          - asset: assets/fonts/Inter-Light.ttf
    - family: InterMedium
      fonts:
          - asset: assets/fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts:
          - asset: assets/fonts/Inter-Regular.ttf
    - family: InterSemiBold
      fonts:
          - asset: assets/fonts/Inter-SemiBold.ttf
    - family: InterThin
      fonts:
          - asset: assets/fonts/Inter-Thin.ttf
    - family: PoppinsBlack
      fonts:
          - asset: assets/fonts/Poppins-Black.ttf
    - family: PoppinsBlackItalic
      fonts:
          - asset: assets/fonts/Poppins-BlackItalic.ttf
    - family: PoppinsBold
      fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
          - asset: assets/fonts/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
          - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
          - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsExtraLight
      fonts:
          - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: PoppinsExtraLightItalic
      fonts:
          - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
    - family: PoppinsItalic
      fonts:
          - asset: assets/fonts/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
          - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsLightItalic
      fonts:
          - asset: assets/fonts/Poppins-LightItalic.ttf
    - family: PoppinsMedium
      fonts:
          - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
          - asset: assets/fonts/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
          - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: PoppinsThin
      fonts:
          - asset: assets/fonts/Poppins-Thin.ttf
    - family: PoppinsThinItalic
      fonts:
          - asset: assets/fonts/Poppins-ThinItalic.ttf
    - family: HeeboRegular
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: HeeboBlack
      fonts:
        - asset: assets/fonts/Heebo-Black.ttf
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboExtraBold
      fonts:
        - asset: assets/fonts/Heebo-ExtraBold.ttf
    - family: HeeboLight
      fonts:
        - asset: assets/fonts/Heebo-Light.ttf
    - family: HeeboThin
      fonts:
        - asset: assets/fonts/Heebo-Thin.ttf
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/manrope-regular.otf
    - family: ManropeMedium
      fonts:
        - asset: assets/fonts/manrope-medium.otf
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/manrope-bold.otf
    - family: ManropeExtraBold
      fonts:
        - asset: assets/fonts/manrope-extrabold.otf
    - family: ManropeLight
      fonts:
        - asset: assets/fonts/manrope-light.otf
    - family: ManropeSemiBold
      fonts:
        - asset: assets/fonts/manrope-semibold.otf
    - family: ManropeThin
      fonts:
        - asset: assets/fonts/manrope-thin.otf


flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Dev"

      android:
        applicationId: "com.peeqlive.dev"

      ios:
        bundleId: "com.peeqlive.dev"

    staging:
      app:
        name: "Staging"
      android:
        applicationId: "com.peeqlive.staging"
      ios:
        bundleId: "com.peeqlive.staging"

    production:
      app:name: "Production"

      android:
        applicationId: "com.peeqlive"
      ios:
        bundleId: "com.peeqlive"